# 2A - Using Variables in C#

Stop sitting there wondering about variables! Want to know how to declare variables using names that won’t get you roasted in a code review? Curious about specifying data types like a hotshot senior C# dev? Ready to assign values—and maybe even assign them while declaring the variables?! If you said “yes” (or even just shrugged curiously), this video’s got you covered. Except for the code review thing, we're not going to talk about that.

I...declare...VARIABLES (in C#)!


0:00 Intro
0:50 Variable Identifiers
1:39 C# Naming Conventions
3:37 Data Types
4:19 C# Declaration Syntax
6:00 Assignment Statements
7:57 Changing a Variable's Value
8:40  Outro
----
This video is part of my course materials for my C#: Level 1 class (CIS162AD) at EMCC, and it's intended to accompany a free eBook: https://timmcmichael.github.io/skimpy-csharp/index.html

Playlist: https://www.youtube.com/playlist?list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU
Files from my videos: https://github.com/timmcmichael/EMCCTimFiles 

GitHub landing page: https://timmcmichael.github.io/

#csharp #coding #beginner #variables #datatypes #assignments #emcc #cis162ad

---------------

# 2B - Arithmetic Operations in Java

Ever wanted to add two numbers together and find out the sum? Tired of having to MANUALLY subtract numbers? Wanting to impress someone at a party with your knowledge of modulo? I'm here for you!

Learn how to create basic arithmetic expressions in Java.

0:00 Intro
0:31 Operations
2:28 Literals vs Variables
3:27 Outputting Results
3:55 Concatenation Operation
5:00 Division and Truncation
6:41 Casting
8:10 Order of Operations
8:25 Modulo
9:35 Outro
----
This video is part of my course materials for my C#: Level 1 class (CIS162AD) at EMCC, and it's intended to accompany a free eBook: https://timmcmichael.github.io/skimpy-csharp/index.html

Playlist: https://www.youtube.com/playlist?list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU
Files from my videos: https://github.com/timmcmichael/EMCCTimFiles 

GitHub landing page: https://timmcmichael.github.io/

#csharp #coding #beginner #visualstudio #helloworld #emcc #cis162ad
---------------

# 2C - User Input in Java

Tired of boring old programs that just say "Hello World"? Want to impress your mom on Mother's Day this year by letting her type her name into a black-and-white console program?

Wait, wait--this whole premise is preposterous! Nobody really thinks "Hello World" is boring...

In this video, we'll learn how accept keyboard input in Java using the Scanner class.

0:00 Intro and Class Creation
1:29 Creating a Scanner Object
2:55 Getting the User's Name
4:38 Getting the User's Age
5:47 User Input Errors
6:22 Adding to an Input Value with +=
7:00 Common Issue: NextLine() After NextInt()
7:50 The Scanner Buffer
9:22 Clearing the Buffer
10:06 Outro
----
This video is part of my course materials for my C#: Level 1 class (CIS162AD) at EMCC, and it's intended to accompany a free eBook: https://timmcmichael.github.io/skimpy-csharp/index.html

Playlist: https://www.youtube.com/playlist?list=PL_Lc2HVYD16Y-vLXkIgggjYrSdF5DEFnU
Files from my videos: https://github.com/timmcmichael/EMCCTimFiles 

GitHub landing page: https://timmcmichael.github.io/

#csharp #coding #beginner #visualstudio #helloworld #emcc #cis162ad