:github-folder: 04%20Decisions

:chapter-number: 4
:source-counter: 0
:imagesdir: ../images/chapter{chapter-number}

== Decisions
[.subtitle]
pass:[<span title='This is "Chapter Four" in binary (base 2)'>Chapter 0100 <sub>2</sub></span>]

include::../_includes/feedback.adoc[]

:sectnums!:
// TODO: Add chapter objectives
=== What's the Point?

* 
* 


_Source code examples from this chapter and associated videos are available on {github-base}/{github-folder}[GitHub^]._

:sectnums:
'''

Decisions, or _branching_ gives our programs the ability to execute different code depending on what's happening as it runs.
At the core of decisions is the concept of _Boolean logic_, which is named after a 19th-century mathematician named George Boole.
Boolean logic is the foundation of the `if` statements that will be the foundation of our branching code.

=== Boolean Expressions

Until now, our programs have all executed very sequentially and predictably--one line of code after another.
How boring!
To give our programs the ability to _branch_ and execute different code based on different conditions, we need to introduce the concept of _decisions_.

In computer programming, a decision is made based on a *Boolean expression*, which is an expression that evaluates to either `true` or `false`.
Think of them as questions that can be answered with a simple "yes" or "no".
_Is this student's GPA high enough to qualify for the scholarship? Has this cell phone customer used all of their data? Did the user type "exit"?_

The `true` or `false` value of a Boolean expression can be used to determine which code block will execute next, so it's important to understand how they work. 


// TODO: Record video on Boolean logic
.Time To Watch!
****
Boolean Logic in C# [COMING SOON!]

// https://youtu.be/npMQkQ2oCAU

// video::npMQkQ2oCAU[youtube, list={playlist}]
// File from video:

// * N/A
****

==== Boolean Values

The simplest way to use Boolean in C# is with the keywords `true` and `false`.
These can be assigned to variables of type `bool`:

[caption="Example {chapter-number}.{counter:source-counter} - "]
.Declaring and assigning Boolean variables in C#.
[source,csharp,linenums]
----
bool isTimAmazing = true;
bool isClassBoring = false;
----

==== Comparison Operations
Also known as _relational operations_, relational operations are expressions that compare two values. 
You will remember them from math class. _Is `x` greater than `y`? Is `a` less than or equal to `10`? Is `c` equal to `d`?_
Relational operators, like <<_math_calculations,arithmetic operators>>, are _binary_ operators that require two operands. 
In other words, we need two values to compare.
In our math class, we could draw symbols that aren't on our keyboard, like a &#8805; for "greater than or equal to."
In C#, where we have to stick with stuff on our keyboard, we use the following symbols:

.C# comparison operators
[cols="1,5", %header, stripes=even,width="50%"]
|===
|*Operator* |*Description*
| `==`
| Equality (checks if two values are equal)
| `!=`
| Inequality (checks if two values are not equal)
| `<`
| Less-than
| `>`
| Greater-than
| `&lt;&#61;`
| Less-than-or-equal-to
| `>=`
| Greater-than-or-equal-to
|===

A relational operation will always evaluate to either `true` or `false`.
We can store that result in a `boolean` variable, as shown below, and we'll also learn how to use these expressions in `if` statements later in this chapter.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.Using comparison operators in C#
[source,csharp,linenums]
----
bool canBuyAlcohol = age >= 21;
bool isNegative = number < 0;
bool isArethaFranklin = name == "Aretha Franklin"; <.>
bool isArethaFranklin2 = name.equals("Aretha Franklin"); <.>
----
<.> This statement uses the `--` operator to check if two strings are equal.
<.> This statement uses the `equals()` method to check if two strings are equal.

These assignment statements work like any other: the expression to the right of the equals symbol is evaluated, and the result is stored in the variable on the left.

NOTE: In C#, we can test string equality with the `==` operator or the `equals()` method. This is different from Java, where we can't use the `==` operator on `String` values. I mention it here because it's a common source of confusion for students who are learning both languages at the same time. 

// TODO: PASTED HERE!!

=== `if` Statements

The `if` statement is the most basic decision-making structure in C#.
It allows us to execute a block of code only if a certain condition is true.

The syntax of an `if` statement is the keyword `if`, followed by a Boolean expression in parentheses, followed by a block of code in curly braces.
If the Boolean expression evaluates to `true`, the block of code will execute.
If the Boolean expression evaluates to `false`, the block of code will be skipped.
In either case the program will continue executing the next line of code after the `if`-block.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A basic `if` statement in C#.
[source,csharp,linenums]
----
int age = 20;
if (age < 21)
{
    Console.WriteLine("You can't buy alcohol.");
}
Console.WriteLine("Keep that in mind when you go to the store!");
----

In this example, the `if` statement checks if the variable `age` is less than `21`.
Since `20` is less than `21`, the Boolean expression evaluates to `true`, and the block of code inside the `if` statement (line 3) is executed--and it prints "You can't buy alcohol."
The program then continues to the next line of code, which prints "Keep that in mind when you go to the store!"

If the value of `age` were `22`, the Boolean expression would evaluate to `false`, and the block of code inside the `if` statement would be skipped.
The program would then continue to the next line of code, which prints "Keep that in mind when you go to the store!"
Line 5 will execute every time the program runs, regardless of the value of `age`.

Keep in mind, the parentheses after the `if` keyword can contain any Boolean expression--not just this simple example.

=== Adding an `else` Block

An `if` statement simply determines whether or not to execute a single block of code.
If we want to choose between two blocks of code, we can add an `else` block to the `if` statement.
The syntax is simple: after the `if` block, add the keyword `else`, followed by a block of code in curly braces.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.An `if-else` statement in C#.
[source,csharp,linenums]
----
int age = 20;
if (age < 21)
{
    Console.WriteLine("You can't buy alcohol.");
}
else {
    Console.WriteLine("You can buy alcohol.");
}
Console.WriteLine("Keep that in mind when you go to the store!");
----

An `if-else` statement will always execute one block of code or the other, but never both.
Basically, it's an either-or situation.

// TODO: Video on if-else statements
.Time To Watch!
****
`if` and `if-else` Statements in C# [COMING SOON!]

// https://youtu.be/YytQwS4F6fE

// video::YytQwS4F6fE[youtube, list={playlist}]
// File from video:

// * Completed code: {github-base}/{github-folder}/MadJokes.cs[`MadJokes.cs`^]

****

.Interesting!
****
C# includes a shorthand form of an if-else statement called the _ternary operator_, which uses the question mark symbol. It's a useful little trick, but it can be confusing for beginners--and for the people reading our code later. We won't look at them in this course, but a web search should turn up plenty of examples if you are curious.

Assignments in my course require you to use complete if-else statements, so you shouldn't use the ternary operator in code you submit to me.
****

=== The `if-else if` Structure

The `if-else` structure is great for choosing between two blocks of code, but what if we have more than two options?
To handle this, we can chain multiple `if-else` statements together.

// TODO: source for WeatherRecord.cs

[caption="Example {chapter-number}.{counter:source-counter} - "]
.`WeatherRecord.cs` (excerpt). Excerpt showing an `if-else if` structure. See {github-base}/{github-folder}[GitHub^] for the complete file.
[source,csharp,linenums]
----
public class WeatherRecord 
{
    // Fields
    private string date;
    private int highTemperature;
    private double averageWindSpeed;

    public string GetTempDescription()
{
        if (this.highTemperature > 90)
{
            return "Hot";
        } else if (this.highTemperature > 70)
{
            return "Warm";
        } else if (this.highTemperature > 50)
{
            return "Cool";
        } else {
            return "Cold";
        }
    }
}
----

In this example, the `GetDescription()` method will return a `string` that describes the weather based on the high temperature of the day.

* If the high temperature is greater than `90`, the method will return "Hot".
* If the high temperature is greater than `70`, the method will return "Warm".
* If the high temperature is greater than `50`, the method will return "Cool".
* If the high temperature is `50` or less, the method will return "Cold".

The code begins with the first statement, and if it evaluates to `true`, the corresponding block of code will execute.
If the first statement evaluates to `false`, the program will move on to the next `else if` statement, and so on.
Once a code block is executed, it will hit a `return` statement, which will exit the method and not evaluate any other blocks of code.
Therefore, only one block of code will execute.
If the program gets through the entire structure without finding a `true` condition, it will execute the block of code in the `else` block, if one is present.

If we're looking at that code critically, we might notice that the `else` block is not strictly necessary. 
We could just put the `return "Cold";` statement at the end of the method, and it would work the same way. 
However, that depends on the logic of the `if-else if` structure and whether or not we're using `return` statements in the blocks of code.

.Interesting!
****
The above example shows one clever use of decisions in an object class. You'd think that a `GetDescription()` method would return the value of a field called `description`, but there is no field. Instead, it just uses a decision structure to return a description based on the `highTemperature` field.
****

In summary, An `if-else if` structure can execute, at most, one block of code. 
If an `else` block is included at the end, it guarantees that exactly one block of code will execute.


// TODO: Video on if-else if statements -- not in objects
.Time To Watch!
****
`if-else if` Statements in C# [COMING SOON!]

// _Note: This video also shows how to use `if` statements in an OOP context, specifically to help with encapsulation._

// // https://youtu.be/ismb63p4N4A

// video::ismb63p4N4A[youtube, list={playlist}]
// Files from video:

// * Starter code: {github-base}/{github-folder}/K12Student.cs[`K12Student.cs`^]
// * Starter file: {github-base}/{github-folder}/K12StudentDemo.cs[`K12StudentDemo.cs`^]

// * Completed code: {github-base}/{github-folder}/K12StudentFinished.cs[`K12StudentFinished.cs`^]
// * Completed code: {github-base}/{github-folder}/K12StudentDemoFinished.cs[`K12StudentDemo.cs`^]
****

=== Nested `if-else` Statements

If we want a block of code to execute only if two different conditions are met, we can place `if` statements inside of each other--which is called _nesting_.
Nested if statements check multiple conditions in a hierarchical way: if one condition is met, it will proceed and check the next condition; if the first condition is not met, it will skip the inner `if` block.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.Basic structure of a nested `if-else` statement in C#.
[source,csharp,linenums]
----
if (condition1)
{
    if (condition2)
{
        // executes if both condition1 and condition2 are true
    }
    else {
        // executes if condition1 is true and condition2 is false
    }
}
else {
    // executes if condition1 is false
}
----

In the example below, the outermost if-else structure checks the high temperature of the day. 
The if-else structures within those blocks check the average wind speed and return an appropriate description.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.`WeatherRecord.cs` (excerpt). Excerpt showing a nested `if-else` structure. See {github-base}/{github-folder}[GitHub^] for the complete file.
[source,csharp,linenums]
----
public String GetFullDescription()
{
        if (this.highTemperature > 90)
{
            if (this.averageWindSpeed > 10)
{
                return "Hot and Windy";
            } else {
                return "Hot";
            }
        } else if (this.highTemperature > 70)
{
            if (this.averageWindSpeed > 10)
{
                return "Warm and Windy";
            } else {
                return "Warm";
            }
        } else if (this.highTemperature > 50)
{
            if (this.averageWindSpeed > 10)
{
                return "Cool and Windy";
            } else {
                return "Cool";
            }
        } else {
            if (this.averageWindSpeed > 10)
{
                return "Cold and Windy";
            } else {
                return "Cold";
            }
        }
    }
----

// TODO: Video on nested if-else statements
.Time To Watch!
****
Nested `if-else` Statements in C# [COMING SOON!]

// https://youtu.be/bKqlmhtaKd8
// video::bKqlmhtaKd8[youtube, list={playlist}]

// _Note: This video also shows how to use `if` statements in an OOP context, specifically to help with encapsulation._

// Files from video:

// * Starter code: {github-base}/{github-folder}/VinylRecord.cs[`VinylRecord.cs`^]
// * Starter code: {github-base}/{github-folder}/VinylRecordDemo.cs[`VinylRecordDemo.cs`^]

// * Completed code: {github-base}/{github-folder}/VinylRecordFinished.cs[`VinylRecordFinished.cs`^]
// * Completed code: {github-base}/{github-folder}/VinylRecordDemoFinished.cs[`VinylRecordDemoFinished.cs`^]
****


=== Using Logical Operators
In addition to the relational operators, C# also includes logical operators we can use to make more complex Boolean expressions.
A logical operator is a binary operation, so it takes two operands--but the operands are Boolean expressions instead of numbers.

.C# logical operators
[cols="1,1,5", %header, stripes=even,width="75%"]
|===
| *Operator* |*Name* |*Description*
|`&&`
|AND 
|Evaluates to `true` if *both* operands are `true`
| `\|\|`
| OR
| Evaluates to `true` if *either* operand is `true`
| `!`
| NOT
| Evaluates to `true` if the operand is `false`; evaluates to `false` if the operand is `true`
|===

These operators can be used to combine multiple Boolean expressions into a single, more complex expression.
For example, we could check if a student is eligible for a scholarship based on both their GPA (3.5 or better) and their age (younger than 25).

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A decision using a logical AND operation in C#.
[source,csharp,linenums]
----
if (gpa >= 3.5 && age < 25)
{
    Console.WriteLine("You qualify for the scholarship!");
}
----

In this example, the `&&` operator is used to combine two Boolean expressions.
The `if` statement will only execute the block of code if both expressions are `true`.

TIP: Often, the logic we create using an AND operation can be implemented using nested if-else statements, and vice versa.

The OR operation is similar, but only one of the expressions needs to be `true` for the entire expression to be `true`.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A decision using a logical OR operation in C#.
[source,csharp,linenums]
----
bool isTimAmazing = false;
bool isClassFun = true;

if (isTimAmazing || isClassFun)
{
    System.out.println("You should take this class!");
}
----

Both operands in an AND or OR operation have to be complete Boolean expressions.
Put another way, each side of the `&&` or `||` operator must be able to evaluate to `true` or `false` on its own.
The following code is a very common beginner mistake and will *not* compile:

`if (percentage >= 80 && < 90)
{ ... }`

This reads like "if the percentage is greater than or equal to 80 and less than 90," but the second part of the expression is not a complete Boolean expression. 
We need to include the variable name and the comparison operator on *both* sides of the `&&` operator.

The NOT operation is a little different, as it only takes one operand (making it a _unary_ operator_, if you're nerdy about words, like I am).
It simply inverts the value of the operand.
If the operand is `true`, the NOT operation will evaluate to `false`.
If the operand is `false`, the NOT operation will evaluate to `true`.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A decision using a logical NOT operation in C#.
[source,csharp,linenums]
----
bool isTimAmazing = false;

if (!isTimAmazing)
{
    System.out.println("At least his mom still loves him!");
}
----

==== Range Checking
There are a lot of situations where we might need to combine multiple conditions to make a decision, but one of the most common is _range checking_.
Range checking means we want to see if a value is within a certain range.

A common example of range checking is to convert a percentage grade to a letter grade.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.Range checking using logical operators in C#.
[source,csharp,linenums]
----
public String GetLetterGrade(int percentage)
{
    if (percentage >= 90 && percentage <= 100)
{
        return "A";
    } else if (percentage >= 80 && percentage < 90)
{
        return "B";
    } else if (percentage >= 70 && percentage < 80)
{
        return "C";
    } else if (percentage >= 60 && percentage < 70)
{
        return "D";
    } else if (percentage >= 0 && percentage < 60)
{
        return "F";
    } else {
        return "Invalid percentage";
    }
}
----

The AND operator `&&` used in this example means that in order to return `"B"`, for example, the percentage must be greater than or equal to `80` _and_ less than `90`.
If either of those conditions is not met, the program will move on to the next `else if` statement.


// TODO: In the future, maybe a video on logical operators and range checking?


=== `switch` Statements

C# includes a structure called a `switch` statement that can be used to choose between multiple options.
It is essentially another way to write an `if-else if` structure, but it can be more readable and easier to write in some situations.
I generally consider `switch` structures to be optional--you can complete all of the assignments in this course without using them--but they are a useful tool to have in your programming toolbox.
And since you see them often in code written by others, it's good to know how they work.

The basic structure of a `switch` statement is as follows:

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A basic `switch` statement in C#.
[source,csharp,linenums]
----
switch (expression)
{
    case value1:
        // Code to be executed if expression equals value1
        break;
    case value2:
        // Code to be executed if expression equals value2
        break;
    case value3:
        // Code to be executed if expression equals value3
        break;
    default:
        // Code to be executed if expression doesn't match any case
}
----

The `expression` in the parentheses after the `switch` keyword is evaluated, and then the program will jump to the `case` that matches the value of the expression.
If there is no match, the program will execute the `default` block, if it is present.

The `break` statement is used to exit the `switch` block due to a behavior of `switch` that can be confusing to beginners, known as _fall-through_.
If we don't include a `break` statement at the end of a `case` block, the program will continue executing the code in the next `case` block, even if the value of the expression doesn't match the `case`.
This can be useful in some situations, but it's generally not what you want, so you'll usually see a `break` statement at the end of each `case` block.

[caption="Example {chapter-number}.{counter:source-counter} - "]
.A `switch` statement in C#.
[source,csharp,linenums]
----
public void TrafficInstructions(string lightColor)
{
    switch (lightColor)
{
        case "red":
            Console.WriteLine("Stop!");
            break;
        case "yellow":
            Console.WriteLine("Slow down!");
            break;
        case "green":
            Console.WriteLine("Go!");
            break;
        default:
            Console.WriteLine("Invalid light color.");
    }
}
----

// TODO: In the future, maybe a video on switch statements?


// NOTE: This solution video: https://youtu.be/Y4_q9RtyH8g


// Intro paragraph or content

// === Topic 1



// .Time To Watch!
// ****
// Title of Youtube video

// video::PR6u4KvAkas[youtube, list={playlist}]
// Files from video:

// * Starter code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
// * Completed code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
// ****


// [caption="Example {chapter-number}.{counter:source-counter} - "]
// .`OutputExample.cs` - Simple console output in C#
// [source,csharp,linenums]
// ----
// Console.Write("In the words of Michael Stipe,");
// Console.WriteLine("Don't go back to Rockville...");
// Console.WriteLine("...and waste another year.");
// ----

// .Class diagram for the `Car` class
// // Image rendered at plantuml.com with the following code:
// [plantuml, format=svg]
// ----
// @startuml
// skinparam classAttributeIconSize 0
// class Car 
{
//   - make:String
//   - model:String
//   +void start()
//   +void stop()
// }
// @enduml
// ----

// IMPORTANT: The Lab Assignments in Canvas can be completed using what we've covered to this point. You might choose to complete that work now, then move onto the next section--which you'll need for the Programming Project.

// .Interesting!
// ****
// This is something // interesting!
// ****



'''

:sectnums!:
=== Check Yourself Before You Wreck Yourself (on the assignments)

==== Can you answer these questions?

****
1. 

2. 

3. 
****
:sectnums:
// TODO: _Sample answers provided in <<_inheritance_,Stuff That's Tacked On The End>>_.