:sectnums!:

:chapter-number: 0
:source-counter: 0
:imagesdir: ../images/chapter{chapter-number}

== Getting Started 
[.subtitle]
pass:[<span title='This is "Chapter Zero" in binary (base 2)'>Chapter 0000 <sub>2</sub></span>]

include::../_includes/feedback.adoc[]

=== What's the Point?

* Understand the common IDE Options for C# development
* Install the tools you need to create C# programs

_Source code examples from this eBook and associated videos are available on {github-base}[GitHub^]._

'''

We'll be learning the fundamental of computer programming using a language called *C#*--we'll learn more about C# in the next chapter.
Software development (coding) requires some tools that probably aren't already installed on your computer.
We're going to look at some popular options for those tools and get them installed.

There are options available for Windows, macOS, and Linux computers.

.Heads Up!
****
C# development on a Chromebook, iPad, or similar device is tricky and not recommended for beginners. 
****

The Canvas course includes some options for students who don't have a computer capable of running the necessary software; you won't need to purchase a new computer to complete this course.
Similarly, #all of the tools we'll use are free (or offer a free version that's adequate for our needs).#

=== Required Tools

We'll need two tools to develop C# programs:

The .NET Software Development Kit (SDK):: This is the software that allows our computer to run C# programs.
An Integrated Development Environment (IDE):: This is the software we'll use to write and test your C# programs.

In general, it's better to install the .NET SDK first, then install your IDE.
However, the IDE you choose may include the .NET SDK, so you may only need to install one thing.

=== Selecting an IDE

An Integrated Development Environment (IDE) is the application we'll use while developing our programs.
Think of it as a word processor--you can write your History essay in Microsoft Word or Google Docs.
They both do pretty much the same thing, and your professor won't know or care which one you use, so picking between them is a matter of preference.
If you're already familiar with a particular IDE--and that IDE supports C#--you can choose to use it for this course. 
If you're new to programming, or if you want to make sure you're using a tool I can help you with, I'll help you decide.

The first consideration is the operating system you're using--*Windows*, *macOS*, or *Linux*--because that will determine which options are available to you.
You can learn C# using any of those operating systems, but be aware that C# has traditionally been focuesed on Windows development, so most of the resources you'll find out there are going to be for Windows.
I'm a Mac user myself, so I'll take care of macOS and Linux learners, but you should know there are many more examples and videos out there for Windows users.
If that's a concern for you, consider using a Windows computer for this course.

I will provide enough information to get started with any of the options below; once you've gotten the hang of how to create and run a project, all of my videos and examples will work the same way regardless of which IDE you're using.

IMPORTANT: The simplest choice for Windows users is *Visual Studio Community*. macOS and Linux users wanting something as user friendly as possible--and as close to Visual Studio Community as possible--should use *JetBrains Rider*. People who like *VS Code* from a different language will have no problem sticking with that.


=== Microsoft Visual Studio Community

Microsoft owns the C# language, so the original and most mature IDE for C# development is *Microsoft Visual Studio*.
It's the _de facto_ standard (meaning, the most common choice) for C# development on Windows
Visual Studio is an enterprise-grade IDE that's used by professional developers all over the world, and is the industry standard for C# development.

IMPORTANT: Microsoft has another product called *Visual Studio Code*, which is a different product and not the same thing as Visual Studio. We'll look at that below.

Visual Studio is the safest choice for Windows users, and it's available in several "editions" to suit different needs; the free version is called *Visual Studio Community* and that's all we'll need for our purposes.

There are two potential reasons to pick an IDE other than Visual Studio:

* It's packed with features, but that includes a ton of stuff we won't need or use. That means it's potentially overwhelming for beginners. I don't think it's a big deal, but if you're after a simpler experience, you might want to look at the other options.
* It's Windows-only, so if you're using macOS or Linux, Visual Studio Community is not an option. _Note: Microsoft used to offer a version of Visual Studio for macOS, but it was discontinued in 2020. I strongly recommend against using that version, even if you can find it._

In most of my own videos, I will be *not* be recorded using Visual Studio, but that's because I'm using a Mac.

=== Other IDE Options

If you don't want to (or can't) use Visual Studio, there are other options available to you.
I have two recommendations.

==== JetBrains Rider

JetBrains Rider is a commericial IDE that is designed specifically for C# development.
The Rider user experience seems to be modeled after Visual Studio--and I mean that in a good way. 

*For most students, this will be the next-best choice (after Visual Studio Community).*

Pros::
* Available for Windows, macOS, and Linux.
* Free for personal (non-commercial) use.
* It's a full-featured IDE that's specifically designed for C# development.
* Similar look and feel to other JetBrains products, so if you've used IntelliJ IDEA or PyCharm, for example, it will feel familiar.

Cons::
* It's not free for commercial use, so if you're planning to use it for a job or to make money, you'll need to pay for a license.
* It's not as popular as Visual Studio or Visual Studio Code, so there are fewer resources available to help you learn how to use it.
* Not as lightweight as VS Code, so it might be slower on older computers.

==== Visual Studio Code

Microsoft also offers a free, open-source IDE with the potentially confusing name *Visual Studio Code*, "VS Code".
It's intended to be a very lightweight, flexible IDE that can be used for many different programming languages.
The base version of VS Code doesn't include much support for C# (or any other language), but you can add that support with an easy-to-install extension.
In fact, it's _so_ lightweight that many people argue that it's not really an IDE at all--it's more of a text editor with some IDE features.

*If you're not already familiar with VS Code, I don't think there's a compelling reason to choose it over Visual Studio Community or JetBrains Rider.*

Pros::
* Available for Windows, macOS, and Linux.
* Free and open-source.
* It's very popular, so there are lots of resources available to help you learn how to use it.
* Supports many different programming languages, so you can use it for other courses or projects.
* Microsoft is agressively improving C# support in VS Code, so it's getting better all the time.

Cons::
* Not as feature-rich as Visual Studio or JetBrains Rider, even with extensions installed.
* Not as user-friendly; created for power users, so it can feel a little primitive to beginners.
* Support for C# is relatively recent; though it's getting better, it's not as robust as the other options.
* Although there are a lot of resources for VS Code, most of those will be for different programming languages.

NOTE: I'll probably record some of my video content using Rider and some using VS Code, so you'll see both in action. VS Code is currently my favorite IDE, but I'm learning Rider so I can hopefully provide support to students who choose either.

==== Something Else?

You're welcome to use any IDE you like, as long as it creates and handles _solution files_ (.sln files), which we'll learn about later. 
But be aware that I will not be able to support you if you run into trouble with an IDE I'm not familiar with.
And one specific caution: *don't rely on a web-based IDE for this course*. 
They're fine for some things, but they're not adequate for the programs we'll create as the course goes on. 
And since web-based IDEs often output weird files--and likely don't support .sln files--you're at risk of getting a zero on work created using such a tool. 
I'm not going to spend time sorting out code that doesn't use standard C# formatting conventions and solution formats.

TIP: You can install and use multiple IDEs on your computer, so you can try them and see which one you like best.


=== Installation Instructions

The linked documents below provide detailed installation instructions--but they are fairly straightforward, so even if some of the details are out of date, you should be able to figure it out.
If that's not the case, email me at {email}.

:sectnums!:

==== Installing Visual Studio Community


// TODO: Install videos for Visual Studio

* https://docs.google.com/document/d/1IMVCBZBH_YtaW-HDzmzXepBeQqXyAYaR1b5GNwB4KkQ/edit?usp=sharing[Install Visual Studio Community on Windows,window=_blank]

_Note Visual Studio Community will automatically install the .NET SDK, so you won't need to install it separately._

==== Installing the .NET SDK and Visual Studio Code

// TODO: Edit VS Code install videos to use with C#

* https://docs.google.com/document/d/13q3nmtAI-KbE-sH9MH5aQlAxv5t-HZ56k1a9TtKsaP0/edit?usp=sharing[Install VS Code for C# on Windows,window=_blank]
* https://docs.google.com/document/d/1IvGJ9DDbGkKj9HxmsjgubvRuOjLNbnepi3HpZjXsH3w/edit?usp=sharing[Install VS Code for C# on macOS,window=_blank]
* https://docs.google.com/document/d/1lo9hoBZkBDux6OKjdbGfXdOw0JaptmNSCZuGBMFNXU8/edit?usp=share_link[Install VS Code for C# on Linux,window=_blank]

==== Installing the .NET SDK and JetBrains Rider

// TODO: Install videos for Rider

* https://docs.google.com/document/d/1bWQuhbEgm0O8jAHeIe53bvNzq3TCnFo02FMi2XUDqXI/edit?usp=sharing[Install JetBrains Rider on any OS,window=_blank]



After installing your IDE and, if necessary, the .NET SDK, you're ready to start creating C# programs!

'''

=== Check Yourself Before You Wreck Yourself (on the assignments)

==== Can you answer these questions?

****
1. What tools do you need to develop C# programs?

2. What does IDE stand for and what is it's role in software development?

3. What IDE did you choose? Why?
****
:sectnums:
_Sample answers provided in <<_getting_started_chapter,Stuff That's Tacked On The End>>_.