// The following corrects the directories if this is included in the index file.
ifeval::["{docname}" == "index"]
:imagesdir: chapter11/images
:sourcedir: chapter11/source
endif::[]
// TODO: Update folder attribute
:github-folder: xxxxxxx

:chapter-number: 11
:source-counter: 0
:imagesdir: ../images/chapter{chapter-number}
== [TOPIC]
pass:[<span title='This is "Chapter Eleven" in binary (base 2)'>Chapter 1011 <sub>2</sub></span>]

include::../_includes/feedback.adoc[]

:sectnums!:
// TODO: Add chapter objectives
=== What's the Point?

* 
* 


_Source code examples from this chapter and associated videos are available on {github-base}/{github-folder}[GitHub^]._

:sectnums:
'''

Intro paragraph or content

=== Topic 1



.Time To Watch!
****
Title of Youtube video

video::PR6u4KvAkas[youtube, list={playlist}]
Files from video:

* Starter code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
* Completed code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
****


[caption="Example {chapter-number}.{counter:source-counter} - "]
.`OutputExample.cs` - Simple console output in C#
[source,csharp,linenums]
----
Console.Write("In the words of Michael Stipe,");
Console.WriteLine("Don't go back to Rockville...");
Console.WriteLine("...and waste another year.");
----

.Class diagram for the `Car` class
// Image can be rendered at plantuml.com if necessary
[plantuml, format=svg]
----
@startuml
skinparam classAttributeIconSize 0
class Car 
{
  - make:String
  - model:String
  +void start()
  +void stop()
}
@enduml
----

IMPORTANT: The Lab Assignments in Canvas can be completed using what we've covered to this point. You might choose to complete that work now, then move onto the next section--which you'll need for the Programming Project.

.Interesting!
****
This is something // interesting!
****



'''

:sectnums!:
=== Check Yourself Before You Wreck Yourself (on the assignments)

==== Can you answer these questions?
// TODO: Add check questions
****
1. 

2. 

3. 
****
:sectnums:
// TODO: _Sample answers provided in <<_xxxxxxx_,Stuff That's Tacked On The End>>_.