:github-folder: 09%20SDLC
:chapter-number: 9
:source-counter: 0
:imagesdir: ../images/chapter{chapter-number}

== Software Development Life Cycle
[.subtitle]
pass:[<span title='This is "Chapter Nine" in binary (base 2)'>Chapter 1001 <sub>2</sub></span>]

include::../_includes/feedback.adoc[]

:sectnums!:
// TODO: Add chapter objectives
=== What's the Point?

* 
* 


_Source code examples from this chapter and associated videos are available on {github-base}/{github-folder}[GitHub^]._

:sectnums:
'''



=== Software Development Process

Learning to write code means creating a lot of programs--mostly small, straightforward programs at first. 
Remember those awful word problems where a train leaves Chicago traveling 40 mph, and another train leaves Denver at 35 mph?
That kind of stuff; but in my course, we don't get too caught up in the math part of it.
But we care *a lot* about understanding the requirements of a program and implementing it successfully.

As our programs become bigger and more complex, we'll need to work within a deliberate design and implementation process in order to keep ourselves organized and focused.
Even the smaller programs we'll develop while learning the basics will benefit from a thoughtful approach beyond just opening a new file and starting to type.
It ensures that we use our time efficiently.
And when we are faced with solving a programming problem that really intimidates us, the process will help make the task more approachable.

For big or small projects, a good general approach to software development is:

Analysis:: Identify the goals and scope of the program. As a rule, keep it small and focused--we can always add features later. *Ask yourself, _What does this program need to do?_*
Testing Plan:: Determine how the final program will be tested. The testing plan will be useful, but most importantly, taking the time to establish a specific testing plan ensures that we thoroughly understand the program before we begin writing code. If we don't know how the program will work, we're not yet ready to begin coding. *Ask yourself, _How will I make sure the program works correctly?_*
Implementation:: Write and test the code. We say that this is an _iterative_ (or "repeating") process, meaning we'll write and test one small piece, staying with it until we know it's good. Then we'll move on to the next piece and repeat. *Ask yourself, _What code do I need in order to get the next part of the program working?_*
Revise or maintain:: If our needs or program requirements change, we'll need to go back to the first step and begin planning the next version. If not, we'll need to monitor that the program continues to perform as expected over time. *Ask yourself, _What's next for this program?_*

We'll flesh out this process as we go--and as our programs become more advanced.


// TODO: Content for SDLC

// Intro paragraph or content

// === Topic 1



// .Time To Watch!
// ****
// Title of Youtube video

// video::PR6u4KvAkas[youtube, list={playlist}]
// Files from video:

// * Starter code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
// * Completed code: {github-base}/github-folder}/HelloWorld.cs[`HelloWorld.cs`^]
// ****


// [caption="Example {chapter-number}.{counter:source-counter} - "]
// .`OutputExample.cs` - Simple console output in C#
// [source,csharp,linenums]
// ----
// Console.Write("In the words of Michael Stipe,");
// Console.WriteLine("Don't go back to Rockville...");
// Console.WriteLine("...and waste another year.");
// ----

// .Class diagram for the `Car` class
// // Image rendered at plantuml.com with the following code:
// [plantuml, format=svg]
// ----
// @startuml
// skinparam classAttributeIconSize 0
// class Car 
{
//   - make:String
//   - model:String
//   +void start()
//   +void stop()
// }
// @enduml
// ----

// IMPORTANT: The Lab Assignments in Canvas can be completed using what we've covered to this point. You might choose to complete that work now, then move onto the next section--which you'll need for the Programming Project.

// .Interesting!
// ****
// This is something // interesting!
// ****



'''

:sectnums!:
=== Check Yourself Before You Wreck Yourself (on the assignments)

==== Can you answer these questions?

****
1. 

2. 

3. 
****
:sectnums:
// TODO: _Sample answers provided in <<_inheritance_,Stuff That's Tacked On The End>>_.